- hosts: webservers
  
  tasks:
    - name: apply
      command: kubectl apply -f /home/pradeep/Desktop/mypythonrepo/k8.yaml
    - name: reload
      command: kubectl rollout restart deployment.apps/hello-python