- hosts: webservers
  
  tasks:
    - name: apply
      command: kubectl apply -f /home/toolsadmin/Desktop/mypythonrepo/deploy.yaml
    - name: reload
      command: kubectl rollout restart deployment.apps/shpl-app